openapi: 3.0.0
info:
  title: Gesha
  description: An API for controlling your expresso machine
  contact:
    name: Luke Channings
  license:
    name: MIT
  version: 1.0.0
servers:
- url: /api
paths:
  /pid/enabled:
    get:
      operationId: get-pid-enabled
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PidEnabled'
          description: OK
      summary: Your GET endpoint
      tags: []
    post:
      operationId: post-pid-enabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PidEnabled'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResult'
          description: OK
  /pid/output:
    get:
      operationId: get-pid-output
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PidOutput'
          description: OK
      summary: Your GET endpoint
      tags: []
  /temp/current:
    get:
      operationId: get-temp
      parameters:
        - explode: true
          in: query
          name: unit
          required: true
          schema:
            enum:
              - c
              - f
            type: string
          style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureItem'
          description: OK
      summary: Your GET endpoint
      tags: []
  /stream/pid/output:
    get:
      operationId: get-stream-pid-output
      responses:
        '200':
          description: "Nothing"
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/PidOutput'
      summary: Your GET endpoint
      tags: []
  /state/current:
    get:
      operationId: get-state-current
      responses:
        '200':
          description: The current state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
  /stream/state:
    get:
      operationId: get-state-stream
      responses:
        '200':
          description: The current state
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/State'
  /temp/target:
    get:
      operationId: get-temp-target
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureTarget'
          description: OK
      summary: Your GET endpoint
      tags: []
    post:
      operationId: post-temp-target
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperatureTarget'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResult'
          description: OK
  /config:
    get:
      description: Get the running app configuration
      operationId: get-config
      parameters: []
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/Config'
          description: OK
      summary: Your GET endpoint
      tags: []
    post:
      description: Update the running app configuration
      operationId: post-config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResult'
          description: OK
  /stream/temp/current:
    get:
      operationId: get-stream-temp-current
      parameters:
        - explode: true
          in: query
          name: unit
          required: true
          schema:
            enum:
              - c
              - f
            type: string
          style: form
        - explode: true
          in: query
          name: sampleRateMs
          required: false
          schema:
            type: number
          style: form
      responses:
        '200':
          content:
            text/event-stream:
              examples:
                CurrentTemperature:
                  value:
                    - 1592685123287
                    - 65.5
              schema:
                $ref: '#/components/schemas/TemperatureItem'
          description: OK
          headers:
            connection:
              explode: false
              schema:
                type: string
              style: simple
      summary: Your GET endpoint
      tags: []
components:
  schemas:
    Config:
      description: The runtime configuration for the app
      example:
        p: p
        spiPort: spiPort
        d: d
        temperatureUnit: temperatureUnit
        i: i
        boilerPin: boilerPin
        temperatureSampleRate: temperatureSampleRate
      properties:
        boilerPin:
          type: string
        spiPort:
          type: string
        temperatureSampleRate:
          type: string
        temperatureUnit:
          type: string
        p:
          type: string
        i:
          type: string
        d:
          type: string
      title: Config
      type: object
    TemperatureItem:
      title: TemperatureItem
      type: object
      properties:
        time:
          type: number
          description: The time at which the temperature was read in unix epoch millis
        tempC:
          type: number
          description: The current temperature in Celcius
        tempF:
          type: number
          description: The current temperature in Fahrenheit
    OperationResult:
      description:
        Indicates if the operation succeeded, and if not, what the error
        was.
      example:
        errorMessage: errorMessage
        ok: true
      properties:
        ok:
          type: boolean
        errorMessage:
          type: string
      required:
        - ok
      title: OperationResult
      type: object
    PidOutput:
      description: The PID output
      type: object
      properties:
        time:
          type: number
          description: The time at which the output was read in unix epoch millis
        output:
          type: number
          description: The current output of the PID
    PidEnabled:
      example:
        enabled: true
      title: PidEnabled
      type: object
      properties:
        enabled:
          type: boolean
        heating:
          type: boolean
    TemperatureTarget:
      description: The target temperature of the boiler
      example:
        target: 95
      properties:
        target:
          type: number
      title: TemperatureTarget
      type: object
    State:
      type: object
      properties:
        currentTemp:
          $ref: '#/components/schemas/TemperatureItem'
        isHeating:
          type: boolean
  securitySchemes: {}
