---
port: "80"
boilerPin: "GPIO7"
spiPort: ""
temperatureSampleRate: "100ms"
temperatureUnit: "C"
temperatureTarget: 98
groupHeadBoilerTempDeltaRatio: 0.91188269
pidFrequency: "1s"
pidAutostart: true
pid:
  - 2
  - 60.0
  - 15.0
themeColor:
  hex: "#954B95"
  hue: 300
verbose: false