# Basic Config
esphome:
  name: ms-silvia-switch
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

logger:
# api:
ota:
web_server:
  port: 80

switch:
  - platform: gpio
    name: Power
    pin: GPIO4
    id: power
    restore_mode: restore_default_off

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "Power Momentary Switch"
    internal: true
    on_press:
      then:
        - switch.toggle: power

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
