= Introduction

Coffee, or _cafè_, is a beverage that has been consumed by humans since the 15th century @hoffmann2014world[p. 48]. Legend says that coffee was discovered by a young 9th-century goatherd named Kaldi @theburro[p. 121], who noticed his goats acting strangely after eating the red "olives" of an evergreen shrub. Kaldi ate the berries himself out of curiosity, and felt energised and mildly intoxicated. Some tellings of the myth mention a Sufi monk passerby who inquired about the boy's behaviour, the boy confessed and the monk took some berries for himself to help him stay alert during his evening devotions @chaldeannewsCoffeeStory. The plant, now known as the _Coffea_ genus, was cultivated in Ethiopia and Yemen where it was called _qahwa_ - a word that at the time referred to wine. This caused coffee to become known as "The Wine of Islam" @superluminalCoffeeWine. The modern European words for coffee are derived from this same root word #sym.dash.em _qahwa_.

Traditional methods of preparing coffee include grinding roasted beans with a mortar and pestle until they are as fine as flour, and then placing the ground coffee in the bottom of a pot (_ibrik_ / _cezve_), which is then heated over a fire. Later,  hot sand became a popular heating method @mochalinoWhatTurkish since the heat is more even than a direct flame. Modern filter coffee can be produced with devices like a Chemex or V60, where ground coffee is placed into a conical paper filter and suspended above a carafe. Hot water is poured into the cone until it is full, the coffee dissolves into the boiling water and drains into the carafe below. Common drip coffee machines work similarly, but the process is automated and less precise.

_Cafè espresso_ is a method of brewing small amounts of strong coffee very quickly. These single servings, known as shots, can be brewed in less than a minute. The best English translation for the word 'espresso' is debated, but based on marketing and etymology it can be taken to mean coffes that is brewed quickly, and on-demand @espresso-etymology (as in _piatto espresso_), as opposed to coffee that has been prepared beforehand like filter coffee in an American diner. The exact definition of what espresso is has changed over time as methods of producing it have evolved. The patent for the first espresso machine was granted to Italian inventor Angelo Moriondo on the 16th of May 1884 @angelo-moriondo-espresso-machine-patent. The machine had a large vertical boiler, a gas burner located at the base, and a chimney running up through the centre of the boiler. The boiler would be half filled with water and heated. Steam pressure from the boiling water could be released through a valve located at the top of the boiler. A separate brew water tank, which is connected to the boiler via a tube controller by a tap, takes water from the boiler and regulates its release into the coffee grounds via a second tap.

The ground coffee is held in a filter basket and slotted into a dedicated space at the bottom of the brew water tank. When pressure in the boiler is sufficient, the barista #sym.dash.em a word that means barkeeper in Italian, but here refers to the person operating the espresso machine #sym.dash.em would turn the tap to fill up the brew water tank, and when the pressure had equalised and water had filled the tank, they could then turn the tap to brew the coffee. This machine used 500-600 grams of ground coffee and produce 50 servings at a time @youtubeAngeloMoriondo. The temperature of the heated water in this machine would have been #sym.approx\100 #sym.degree.c since it used steam pressure to push the water through the coffee. The water that remained liquid must be close to 100 #sym.degree.c, although some heat would have been lost as the water travelled to the coffee.

In 1938, Achille Gaggia #sym.dash.em another Italian inventor famous within the espresso community #sym.dash.em adapted Moriondo's multi-serving machine design into a single shot design. He patented the portafilter (a portmanteau of "portable" and "filter"), a removable device made up of a handle, a detachable filter basket where the ground coffee is placed, and a spout. Portafilters come in both single and double-spout varieties, allowing the barista to produce more than one shot at a time when necessary. There are also "naked portafilters", which do not have a spout but instead have an open bottom through which the brewed espresso can drain omnidirectionally.

Moriondo's brew tank is replaced by the grouphead in Gaggia's design, a block that the portafilter locks to. Water flows directly from the boiler and through the grouphead; the flow of water was originally controlled by a manual value, and later an electrical solenoid valve. The water from the grouphead is dispersed over the portafilter basket using a dispersion screen, also known as the shower screen.

In 1947, following the success of his first machine, Gaggia recieved the first patent for a piston-driven extraction mechanism @gaggianaHistory. This design uses a lever to compress a spring, which when released forces a piston through a water chamber and into the ground coffee. The modern colloquial term for producing a shot of espresso is "pulling a shot", in reference to the piston machine's lever @seriouseatsCoffeeJargon. This innovation allowed the brewing water to be below 100 degrees celsius, since steam pressure was no longer needed. The spring usually produced higher brew pressures (9-10 bars, or 116-145psi) than the steam method (which can vary depending on the pressure valve, but is reported as being between 1.5-2 bars, or 7-22psi @smithsonianmagLongHistory), which means that the coffee must be ground finer in order to pull a shot in the same time. As the coffee is ground more finely, the increased surface area allows more flavour (measured in Total Dissolved Solids, TDS) to be extracted.

In 1961 the Faema E61 @wikipediaE61 was released, which was the first espresso machine to use an electrical pump. The design for the E61 grouphead and portafilter became a standard in espresso machines across the industry, meaning portafilters and shower screens can be used interchangeably between a variety of espresso machines today.

In 1998, the Italian Espresso National Institute was founded to safeguard traditional Italian espresso. It published a technical definition for "Certified Italian Espresso" that same year (@certified-italian-espresso-parameters). The parameters published by the IENI describe a "recipe" for Traditional Italian Espresso as it is still being served in Italy today. This traditional espresso is typically made with darkly roasted beans which are more porous and brittle, making them easier to extract @hoffmann2014world[p. 105]. This style of espresso is typically a blend of espresso beans, for example 80% _Coffea arabica_ and 20% _Coffea canephora_ is a common blend.

#figure(
    table(
        columns: 2,
        rows: 9,
        [*Necessary portion of ground coffee*], [ 7 g #sym.plus.minus 0.5],
        [*Exit temperature of water from the unit*], [ 88 #sym.degree.c #sym.plus.minus 2 #sym.degree.c],
        [*Temperature of the drink in the cup*], [67 #sym.degree.c #sym.plus.minus 3 #sym.degree.c],
        [*Entry water pressure*], [9 bar #sym.plus.minus 1],
        [*Percolation time*], [25 seconds #sym.plus.minus 5 seconds],
        [*Viscosity at 45#sym.degree.c*], [ #sym.gt 1.5 mPa s],
        [*Total fat*], [ #sym.gt 2 mg/ml],
        [*Caffeine*], [< 100 mg/cup],
        [*Millilitres in the cup (including froth)*],[25 ml #sym.plus.minus 2.5]),
    caption: [Certified Italian Espresso parameters @instituto-nazionale-espresso-italiano-no-date, scaled for 1 serving]
) <certified-italian-espresso-parameters>

 However, as coffee culture expands into a global phenomena, experimentation and individuality in brewing has gained popularity in the last few decades. Strict adherence to these standards is not always expected by coffee experts and hobby baristas, nor is it always preferred by untrained drinkers. _Coffea canephora_, used in traditional espresso blends, is cheaper to produce but is said to have a "burnt rubber" taste in the cup. @hoffmann2014world[p. 12]. Known popularly as Robusta coffee, _canephora_ beans are commonly associated with cheap and low quality commodity coffee.

_Commodity coffee_ is used to refer to coffee that is produced and consumed as a commodity like sugar or flour, wherein  scale and efficiency are more important than the quality or origin of the beans. Often commodity beans are a blend from many producers, rendering the beans impossible to trace back to their grower. _Speciality coffee_ @specialty-coffee juxtaposes commodity coffee, emphasising quality and traceability. Speciality coffee has more in common with the fine wine market than the sugar or flour markets: low-volume and single origin coffees are preffered by specialty coffeehouses, and the coffee roasters therefore tend to have a direct relationship with small, often family-owned coffee producers. Today, coffee enthiusiasts refer to three waves of coffee consumption. The first and second waves saw the popularisation and commoditisation of coffee throughout Europe: the first wave introduced coffee to Europe in the late Medieval period, while the second wave began with the invention of espresso at the turn of the 20th century. In the last few decades, a third wave of coffee has seen an explosion in choice of high quality coffees as well as the way these coffees are prepared. The espresso community has adopted lighter roast coffees, not just the dark roasts that are a hallmark of Traditional Italian Espresso.

Extraction temperature (temperature of the water as it exits the unit and contacts the coffee) has a large impact on the quality of the final cup. Increasing temperature increases the extraction of soluble compounds in the coffee, of which only #sym.approx 30% are water soluble @understanding-extraction. Dark roasts are normally extracted between 85-95 #sym.degree.c. Lighter roasted beans are harder to extract, and temperatures of 90-95 #sym.degree.c are recommended @bh-espresso-temperature-extraction. The ability to set the extraction temperature is therefore valuable. Temperature consistency is also important, and whilst controlled temperature gradients may be desirable, uncontrolled temperature gradients make shots impossible to reproduce and risk the temperature falling out of the narrowly-defined acceptable range.

More soluble compounds are extracted at higher temperatures @salamanca2017extraction. Extracting all 30% of solubles into the beverage would extract bad-tasting compounds that have been described as "bitter" and "papery" @understanding-extraction: this is known as _over extraction_. Extracting fewer soluble compounds, which can be done by pulling a shot for a short time or grinding too coarsely, produces a sour-tasting coffee. This is called _under extraction_.

Unlike dose (the amount of coffee used), grind size, and extraction time, the extraction temperature is not under the direct control of the barista. This means that the barista will not be able to consistently pull a shot of the same coffee. These changes in temperature can lead to under-extraction or over-extraction of any particular shot of espresso, leading to an inconsistent taste despite use of the same beans, at the same grind size, and with the same machine and barista. The ideal temperature for the brew will depend on the specific coffee's roast level, with darker roast beans needing higher temperatures and medium roast beans needing lower temperatures. When the extraction temperature is not known to the barista, they will not be able to improve their extraction. As third-wave expert and hobbyist baristas strive for better results and more interesting taste profiles, increased control over the brewing parameters are highly sought-after.

This project will focus on a consumer-grade espresso machine: the Rancilio _Silvia_. This machine has a single boiler which has the dual purpose of heating water for brewing espresso and producing steam, which when expelled through a steam wand can be used to produce steamed milk. Espresso combined with varying quantities and textures of steamed milk can be used to make popular drinks such as the latte, cappuccino, flat white, and others. This machine is a mid-range option when compared to all coffee brewing systems, but is considered entry-level for home espresso brewing. It is a popular and accessible choice in Europe and North America, and the results of this study are therefore generalizable to a large consumer share.

The Italian Espresso National Institute defines one more parameter in its definition of espresso: brew pressure @andueza2002influence. As with all other aspects of the brewing process, pressure profiling and flow profiling are a current topic of research amongst coffee enthusiasts @andueza2007influence. Although water pressure will affect the espresso made by any machine, most entry-level and mid-range home espresso machines, including the Rancilio Silvia, do not have a mechanism for changing the pressure. This is a feature of higher end commercial and "prosumer" espresso machines. Unlike pressure profiling, extraction temperature stability can be improved without expensive hardware.

The boiler temperature and consequently the extraction temperature for the Silvia is controlled by a temperature-sensitive actuator (TSA), which is either open or closed (heating or not heating the boiler) when the boiler temperature is below or above 100 #sym.degree.c respectively. The temperature sensor is fixed to the outside of the boiler and the heat generated within the heating element of the boiler takes some time to travel from the element to the TSA. Because of this _temperature lag_ between the sensor and the heating element, the boiler will continue to heat up after the TSA has closed. The consequence of this is that the boiler temperature can vary by #sym.approx\10 #sym.degree.c (@threshold-control) from one shot to the next, depending how long ago the boiler was turned off. I call the machine's default method of controlling temperature "threshold control", since its behaviour is determined by the boiler temperature crossing a threshold.

Most espresso machines need to be pre-heated before coffee can be brewed because some of the heat from the boiler will escape into the machine's casing, causing the brew water to be cooled as it travels from the boiler to the coffee. A machine that has been up to temperature for a period will heat up the machine's chassis, which reduces the cooling effect. Machines vary in the amount of time required for them to pre-heat, and the exact temperature difference between a cold machine and a pre-heated machine is not known.

#figure(
    image("../diagrams/boiler_temp_sawtooth.svg", width: 90%),
    caption: [100 #sym.degree.c Threshold Control Method],
) <threshold-control>

In this project, I plan to improve results in the problem of inconsistent and opaque extraction temperatures when brewing with the Rancilio Silvia. This will include:

1. Hardware modifications to enable programmatic control over the machine's power and heating element, and temperature sensors on the boiler and grouphead.
2. Software to model the machine's state and provide an interface (API) for interacting with it, as well as a mechanism to store and query past machine states constituting a rich dataset of the machine's behaviour.
3. An end-user interface for viewing real-time temperature data, recording when a shot is being pulled (further contributing to a dataset), and controlling the machine's behaviour.
4. Data analysis to learn about the behaviour of the machine through gathered data
5. The production of predictive models to enable a new predictive temperature control method

= Existing solutions

A common method of mitigating this problem is *temperature surfing*. The barista will intentionally discharge hot water through the grouphead until the heating indicator the machine illuminates, and then waits 10 seconds after the indicator turns off before pulling their shot. By following this procedure the boiler will be at approximately the same point in the heating cycle each time the barista pulls a shot. This results in a more consistent temperature, but they won't be able to know or adjust the extraction temperature, only that it is approximately the same each time a shot is pulled.

Another solution that relies on similar hardware changes to the ones I propose is the addition of a PID controller. Popular projects such as PID Silvia @pid-silvia, Auber PID @auberpid, and meCoffee @mecoffee provide hardware modification kits that keep the boiler temperature stable using a PID controller.

I do not believe that a PID solution will perform well considering the temperature lag I have described, as even a well tuned PID controller will not accurately control a system where there is significant delay in measurements @pid-delay. These projects may use a lower latency temperature sensor, or perhaps mount a sensor closer to the boiler's heating element, but this remains to be seen. I note specifically the graph shown in the meCoffee product page @mecoffee-graph, which shows a temperature variance of 20 #sym.degree.c with the unmodified Silvia, which contradict my measurements (@threshold-control) that show the variance is closer to 10 #sym.degree.c. A PID controller is a control system that works best when the sensor lag is as close to zero as possible, and when there is a lag the PID controller will have a similar performance profile to the threshold control method.

My proposed solution uses a predictive modelling approach which may not have the same sensitivity to sensor lag that a PID controller will suffer from.
