/*
 * gesha
 *
 * An API for controlling your expresso machine
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"
)

// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface {
	GetConfig(http.ResponseWriter, *http.Request)
	GetPidEnabled(http.ResponseWriter, *http.Request)
	GetPidOutput(http.ResponseWriter, *http.Request)
	GetStreamPidOutput(http.ResponseWriter, *http.Request)
	GetStreamTempCurrent(http.ResponseWriter, *http.Request)
	GetTemp(http.ResponseWriter, *http.Request)
	GetTempTarget(http.ResponseWriter, *http.Request)
	PostConfig(http.ResponseWriter, *http.Request)
	PostPidEnabled(http.ResponseWriter, *http.Request)
	PostTempTarget(http.ResponseWriter, *http.Request)
}

// DefaultAPIServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface {
	GetConfig() (interface{}, error)
	GetPidEnabled() (interface{}, error)
	GetPidOutput() (interface{}, error)
	GetStreamPidOutput(w http.ResponseWriter, r *http.Request)
	GetStreamTempCurrent(w http.ResponseWriter, r *http.Request)
	GetTemp(string) (interface{}, error)
	GetTempTarget() (interface{}, error)
	PostConfig(Config) (interface{}, error)
	PostPidEnabled(PidEnabled) (interface{}, error)
	PostTempTarget(TemperatureTarget) (interface{}, error)
}
