/*
 * gesha
 *
 * An API for controlling your expresso machine
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"encoding/json"
	"net/http"
	"strings"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultAPIServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultAPIServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"GetConfig",
			strings.ToUpper("Get"),
			"/api/config",
			c.GetConfig,
		},
		{
			"GetPidEnabled",
			strings.ToUpper("Get"),
			"/api/pid/enabled",
			c.GetPidEnabled,
		},
		{
			"GetPidOutput",
			strings.ToUpper("Get"),
			"/api/pid/output",
			c.GetPidOutput,
		},
		{
			"GetStreamPidOutput",
			strings.ToUpper("Get"),
			"/api/stream/pid/output",
			c.GetStreamPidOutput,
		},
		{
			"GetStreamTempCurrent",
			strings.ToUpper("Get"),
			"/api/stream/temp/current",
			c.GetStreamTempCurrent,
		},
		{
			"GetTemp",
			strings.ToUpper("Get"),
			"/api/temp/current",
			c.GetTemp,
		},
		{
			"GetTempTarget",
			strings.ToUpper("Get"),
			"/api/temp/target",
			c.GetTempTarget,
		},
		{
			"PostConfig",
			strings.ToUpper("Post"),
			"/api/config",
			c.PostConfig,
		},
		{
			"PostPidEnabled",
			strings.ToUpper("Post"),
			"/api/pid/enabled",
			c.PostPidEnabled,
		},
		{
			"PostTempTarget",
			strings.ToUpper("Post"),
			"/api/temp/target",
			c.PostTempTarget,
		},
	}
}

// GetConfig - Your GET endpoint
func (c *DefaultApiController) GetConfig(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetConfig()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetPidEnabled - Your GET endpoint
func (c *DefaultApiController) GetPidEnabled(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetPidEnabled()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetPidOutput - Your GET endpoint
func (c *DefaultApiController) GetPidOutput(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetPidOutput()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetStreamPidOutput - Your GET endpoint
func (c *DefaultApiController) GetStreamPidOutput(w http.ResponseWriter, r *http.Request) {
	c.service.GetStreamPidOutput(w, r)
}

// GetStreamTempCurrent - Your GET endpoint
func (c *DefaultApiController) GetStreamTempCurrent(w http.ResponseWriter, r *http.Request) {
	c.service.GetStreamTempCurrent(w, r)
}

// GetTemp - Your GET endpoint
func (c *DefaultApiController) GetTemp(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	unit := query.Get("unit")
	result, err := c.service.GetTemp(unit)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetTempTarget - Your GET endpoint
func (c *DefaultApiController) GetTempTarget(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetTempTarget()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// PostConfig -
func (c *DefaultApiController) PostConfig(w http.ResponseWriter, r *http.Request) {
	config := &Config{}
	if err := json.NewDecoder(r.Body).Decode(&config); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.PostConfig(*config)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// PostPidEnabled -
func (c *DefaultApiController) PostPidEnabled(w http.ResponseWriter, r *http.Request) {
	pidEnabled := &PidEnabled{}
	if err := json.NewDecoder(r.Body).Decode(&pidEnabled); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.PostPidEnabled(*pidEnabled)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// PostTempTarget -
func (c *DefaultApiController) PostTempTarget(w http.ResponseWriter, r *http.Request) {
	temperatureTarget := &TemperatureTarget{}
	if err := json.NewDecoder(r.Body).Decode(&temperatureTarget); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.PostTempTarget(*temperatureTarget)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
