/*
 * gesha
 *
 * An API for controlling your expresso machine
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// TemperatureTarget - The target temperature of the boiler
type TemperatureTarget struct {

	Target float32 `json:"target,omitempty"`
}
