/*
 * gesha
 *
 * An API for controlling your expresso machine
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type PidEnabled struct {

	Enabled bool `json:"enabled,omitempty"`
}
