/*
 * gesha
 *
 * An API for controlling your expresso machine
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// Config - The runtime configuration for the app
type Config struct {

	BoilerPin string `json:"boilerPin,omitempty"`

	SpiPort string `json:"spiPort,omitempty"`

	TemperatureSampleRate string `json:"temperatureSampleRate,omitempty"`

	TemperatureUnit string `json:"temperatureUnit,omitempty"`

	P string `json:"p,omitempty"`

	I string `json:"i,omitempty"`

	D string `json:"d,omitempty"`
}
