on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Install dependencies
        run: sudo apt-get install -y upx
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: make all
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset-darwin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/darwin/gesha
          asset_name: gesha-darwin
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset-arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/linux-arm/gesha
          asset_name: gesha-linux-arm
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/linux-arm64/gesha
          asset_name: gesha-linux-arm64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/linux-amd64/gesha
          asset_name: gesha-linux-amd64
          asset_content_type: application/octet-stream
